/** Shared interface copy. Business rules and narrative live in story.ts. */
export const COPY = {
  brand: 'Global Pursuit League', subtitle: 'A business simulation',
  welcome: 'Every promise has a future.',
  premise: 'Lead a client engagement from the first conversation to delivery. Read the room, find the evidence and make the calls. The people — and your promises — stay with you.',
  role: 'You are the pursuit lead.', format: '5 chapters · 18 decisions · Your progress saved',
  duration: 'Allow around 70–90 minutes. You can play one chapter at a time.',
  start: 'Begin your engagement', resume: 'Continue your engagement', journey: 'Your journey', enter: 'Enter chapter', back: 'Return to your activity',
  next: 'Continue', begin: 'Begin the chapter', choices: 'Explore your approaches', commit: 'Commit to this approach', send: 'Send this reply', investigate: 'Investigate these questions', assemble: 'Commit this plan', setup: 'Start the pursuit',
  record: 'Your account file', help: 'How to play', settings: 'Preferences', close: 'Close', restart: 'Start a new engagement',
  restartWarning: 'This replaces the saved engagement, reflections and personal action plan in this browser. Copy your run code to keep committed decisions. Download your debrief before restarting to keep your notes; run codes do not include them.',
  chosen: 'Your commitment', why: 'What this teaches', forward: 'Carry this forward', outcome: 'The consequence', known: 'What you know',
  emptyEvidence: 'No findings yet. Investigate a question to add evidence to this file.', emptyLedger: 'Your commitments will appear here as the engagement develops.', emptyHistory: 'Your decision record begins with your first commitment.',
  unavailable: 'This approach needs evidence or commitments you have not established on this path.',
  cost: 'What you commit', audit: 'Review the brief', selected: 'Selected',
  reflectionNote: 'Your notebook. Nothing written here reaches the deal.',
  code: 'Save or restore a run', codeHelp: 'A run code preserves committed decisions, not an unfinished selection, reflection, personal action plan or the exact screen. This browser saves those automatically when storage is available.',
  restore: 'Restore engagement', copy: 'Copy run code', copied: 'Copied', noCode: 'Choose your starting team to create a run code.',
  saving: 'Browser saving is unavailable. Keep your run code before closing this page.',
  conflict: 'This browser and your learning platform have different engagements. Choose the one you want to continue.',
  invalidLms: 'The learning platform’s saved run could not be restored. You can start again or enter another run code.',
  fiction: 'A fictional training scenario. Photographs feature models, not the named characters or Accenture employees.',
  /** Business position. Shown as the state of the deal, never as the player's score. */
  dimensions: {
    win: { label: 'Winnability', short: 'Win', question: 'Can we win it?' },
    profit: { label: 'Profitability', short: 'Profit', question: 'Is it worth winning?' },
    deliver: { label: 'Deliverability', short: 'Deliver', question: 'Can we deliver it?' },
  },
  position: 'Business position',
  positionNote: 'The state of the deal, not a score. It moves only after you commit.',
  sound: 'Sound',
  stage: {
    kicker: 'An interactive business drama',
    client: 'Orion Retail · 210 stores',
    caseFile: 'Case file',
    decision: 'Decision',
    yourTeam: 'Your team',
    pickOne: 'Choose one',
    pickExactly: 'Choose exactly',
    selected: 'selected',
    commits: 'What it costs you',
    offers: 'Gives you',
    givesUp: 'Gives up',
    effort: 'Effort',
    investment: 'Investment',
    lockedTitle: 'Not open to you on this path',
    needs: 'Needs',
    needsOne: 'Needs one of',
    board: 'Discovery board',
    boardHint: 'Pin the questions you will spend your time on.',
    plan: 'The plan',
    slot: 'Unfunded',
    replyAs: 'Your reply',
    online: 'Messaging',
    onCall: 'On the call',
    you: 'You',
    youRole: 'Pursuit lead',
    cameraOff: 'Camera off',
    steer: 'In your ear',
    asks: 'asks',
    read: '’s read',
    noticed: 'noticed',
    nothingNoted: 'Nothing noted yet.',
    afterwards: 'afterwards',
    afterwardsAlone: 'Afterwards',
    evidence: 'On your record',
    evidenceNone: 'Nothing on file bears on these arguments.',
    builtOn: 'Built on',
    builtOnOneOf: 'Built on any one of',
    andOneOf: 'And one of',
    earned: 'On file',
    missing: 'Not on file',
    notInRecord: 'Not in your record',
    liabilityGate: 'Nothing you promised calls for this.',
    committed: 'Committed',
    youChose: 'You chose',
    becauseFixed: 'This approach lands the same way whatever came before it.',
    happened: 'What happened',
    changed: 'What is now different',
    because: 'Why it landed this way',
    becauseHeld: 'Your record shows',
    becauseLacked: 'Your record does not show',
    becauseDims: 'And the deal stood at',
    missedWith: 'It would have landed differently with',
    missedOneOf: 'one of',
    missedWithout: 'or without',
    becauseNone: 'Your record matched none of the other ways this could have landed.',
    atLeast: 'or more',
    atMost: 'or less',
    remembered: 'Added to your file',
    lessonFrom: 'What they would tell you',
    forward: 'Carry this forward',
    closed: 'Filed',
    milestone: 'Stage reached',
    chapterMoved: 'How the chapter moved the deal',
    agenda: 'In this act',
    advisorFor: 'With you on this act',
    reflect: 'Between decisions',
    objective: 'The ask',
    matters: 'What matters to them',
    consider: 'Questions to consider',
    incoming: 'Incoming call',
    beforeCall: 'Before you join',
    joinCall: 'Join the call',
    message: 'Message',
    messages: 'New messages',
    openThread: 'Open the thread',
    facing: 'Across the table',
    makeCase: 'Prepare your case',
    noResponse: 'Continue without a response',
    episodes: 'Five acts, one engagement',
    done: 'Complete',
    here: 'You are here',
    ahead: 'Ahead',
    endedHere: 'Ended here',
    notReached: 'Not reached on this path',
    review: 'Review this act',
    chapterReview: 'Decisions in chapter',
    record: 'Every call you made, in order.',
    revealThreads: 'Show the chains without answering',
    fileLink: 'Open your updated account file',
  },
  helpItems: [
    ['Read, decide, discover', 'Each decision opens with a brief. Read the evidence, choose an approach and commit. You will then see what happened and why.'],
    ['Five connected chapters', 'The journey takes you from finding a client to delivering your promise. A chapter briefing tells you where you are going; a debrief shows what you learned.'],
    ['Decisions have a memory', 'Earlier discoveries and commitments can change later conversations.'],
    ['Keep your account file close', 'Reopen the brief, inspect earned evidence and review your commitments at any time. Reviewing information never changes your decision.'],
    ['Play at your pace', 'There is no timer and no audio required. Use Tab to move, Space to select and Enter to activate buttons. Your draft is saved in this browser.'],
  ],
  glossary: [
    ['Sponsor', 'The client leader championing the engagement. Support is valuable, but does not replace agreement from the people affected.'],
    ['Qualification', 'Testing whether a potential engagement merits further investment, using evidence rather than enthusiasm alone.'],
    ['Scope', 'The work and responsibilities included in a commitment — and the boundaries around them.'],
    ['Margin', 'What remains from revenue after the costs of delivering the work.'],
    ['Procurement', 'The client function managing the buying process, commercial terms and supplier selection.'],
    ['Handover', 'Transferring the context, decisions, promises and responsibilities to the team delivering the work.'],
  ],
} as const;
