/** Shared interface copy. Business rules and narrative live in story.ts. */
export const COPY = {
  brand: 'Global Pursuit League', subtitle: 'A business simulation',
  welcome: 'Every promise has a future.',
  premise: 'Lead a client engagement from the first conversation to delivery. Read the room, find the evidence and make the calls. The people — and your promises — stay with you.',
  role: 'You are the pursuit lead.', format: '5 chapters · 18 decisions · Your progress saved',
  duration: 'Allow around 70–90 minutes. You can play one chapter at a time.',
  start: 'Begin your engagement', resume: 'Continue your engagement', journey: 'Your journey', enter: 'Enter chapter', back: 'Return to your activity',
  next: 'Continue', begin: 'Begin the chapter', choices: 'Explore your approaches', commit: 'Commit to this approach', send: 'Send this reply', investigate: 'Investigate these questions', assemble: 'Commit this plan', setup: 'Start the pursuit',
  record: 'Your account file', help: 'How to play', settings: 'Preferences', close: 'Close', restart: 'Start a new engagement',
  restartWarning: 'This replaces the saved engagement in this browser. Copy your run code first if you want to keep your decisions.',
  chosen: 'Your commitment', why: 'What this teaches', forward: 'Carry this forward', outcome: 'The consequence', known: 'What you know',
  emptyEvidence: 'No findings yet. Investigate a question to add evidence to this file.', emptyLedger: 'Your commitments will appear here as the engagement develops.', emptyHistory: 'Your decision record begins with your first commitment.',
  unavailable: 'This approach needs evidence or commitments you have not established on this path.',
  cost: 'What you commit', audit: 'Review the brief', selected: 'Selected',
  reflectionNote: 'A moment to reflect, not a test. Your response does not affect the outcome.',
  code: 'Save or restore a run', codeHelp: 'A run code preserves committed decisions, not an unfinished selection, reflection or the exact screen. This browser saves those automatically when storage is available.',
  restore: 'Restore engagement', copy: 'Copy run code', copied: 'Copied', noCode: 'Choose your starting team to create a run code.',
  saving: 'Browser saving is unavailable. Keep your run code before closing this page.',
  conflict: 'This browser and your learning platform have different engagements. Choose the one you want to continue.',
  invalidLms: 'The learning platform’s saved run could not be restored. You can start again or enter another run code.',
  fiction: 'A fictional training scenario. Photographs feature models, not the named characters or Accenture employees.',
  helpItems: [
    ['Read, decide, discover', 'Each activity opens with a brief. Read the evidence, choose an approach and commit. You will then see what happened and why.'],
    ['Five connected chapters', 'The journey takes you from finding a client to delivering your promise. A chapter briefing tells you where you are going; a debrief shows what you learned.'],
    ['Decisions have a memory', 'Earlier discoveries and commitments can change later conversations. There is no single approach that works in every situation.'],
    ['Keep your account file close', 'Reopen the brief, inspect earned evidence and review your commitments at any time. Reviewing information never changes your decision.'],
    ['Play at your pace', 'There is no timer and no audio required. Use Tab to move, Space to select and Enter to activate buttons. Your draft is saved in this browser.'],
  ],
  glossary: [
    ['Sponsor', 'The client leader championing the engagement. Support is valuable, but does not replace agreement from the people affected.'],
    ['Qualification', 'Testing whether a potential engagement merits further investment, using evidence rather than enthusiasm alone.'],
    ['Scope', 'The work and responsibilities included in a commitment — and the boundaries around them.'],
    ['Margin', 'What remains from revenue after the costs of delivering the work.'],
    ['Procurement', 'The client function managing the buying process, commercial terms and supplier selection.'],
    ['Handover', 'Transferring the context, decisions, promises and responsibilities to the team delivering the work.'],
  ],
} as const;
